---
driver:
  name: qemu

provisioner:
  name: chef_zero

platforms:
  - name: default
#    driver:
#      display: sdl

suites:
  - name: stretch
    driver:
      image:
        - file: stretch.qcow2
        - file: /tmp/new.qcow2
          snapshot: off
    run_list:
      - recipe[kitchen-qemu-images::stretch-attributes]
      - recipe[kitchen-qemu-images::format]
      - recipe[kitchen-qemu-images::debootstrap]
      - recipe[kitchen-qemu-images::stretch]
      - recipe[kitchen-qemu-images::bootstrap]
      - recipe[kitchen-qemu-images::done]
  - name: jessie
    driver:
      image:
        - file: jessie.qcow2
        - file: /tmp/new.qcow2
          snapshot: off
    run_list:
      - recipe[kitchen-qemu-images::jessie-attributes]
      - recipe[kitchen-qemu-images::format]
      - recipe[kitchen-qemu-images::debootstrap]
      - recipe[kitchen-qemu-images::jessie]
      - recipe[kitchen-qemu-images::bootstrap]
      - recipe[kitchen-qemu-images::done]
  - name: wheezy
    driver:
      image:
        - file: wheezy.qcow2
        - file: /tmp/new.qcow2
          snapshot: off
    run_list:
      - recipe[kitchen-qemu-images::wheezy-attributes]
      - recipe[kitchen-qemu-images::format]
      - recipe[kitchen-qemu-images::debootstrap]
      - recipe[kitchen-qemu-images::wheezy]
      - recipe[kitchen-qemu-images::bootstrap]
      - recipe[kitchen-qemu-images::done]
  - name: trusty
    driver:
      image:
        - file: trusty.qcow2
        - file: /tmp/new.qcow2
          snapshot: off
    run_list:
      - recipe[kitchen-qemu-images::trusty-attributes]
      - recipe[kitchen-qemu-images::format]
      - recipe[kitchen-qemu-images::debootstrap]
      - recipe[kitchen-qemu-images::trusty]
      - recipe[kitchen-qemu-images::bootstrap]
      - recipe[kitchen-qemu-images::done]
  - name: xenial
    driver:
      image:
        - file: xenial.qcow2
        - file: /tmp/new.qcow2
          snapshot: off
    run_list:
      - recipe[kitchen-qemu-images::xenial-attributes]
      - recipe[kitchen-qemu-images::format]
      - recipe[kitchen-qemu-images::debootstrap]
      - recipe[kitchen-qemu-images::xenial]
      - recipe[kitchen-qemu-images::bootstrap]
      - recipe[kitchen-qemu-images::done]
  - name: centos7
    driver:
      memory: 1024
      image:
        - file: centos7.qcow2
        - file: /tmp/new.qcow2
          snapshot: false
    run_list:
      - recipe[kitchen-qemu-images::centos7-attributes]
      - recipe[kitchen-qemu-images::format]
      - recipe[kitchen-qemu-images::yum]
      - recipe[kitchen-qemu-images::centos7]
      - recipe[kitchen-qemu-images::bootstrap]
      - recipe[kitchen-qemu-images::done]
  - name: freebsd10
    driver:
      display: sdl
      image:
        - file: freebsd10.qcow2
        - file: /tmp/new.qcow2
          snapshot: off
    run_list:
      - recipe[kitchen-qemu-images::freebsd10-attributes]
      - recipe[kitchen-qemu-images::bsdinstall]
  - name: test
    driver:
      display: sdl
      image: /tmp/new.qcow2
  - name: mutate
    driver:
      display: sdl
      image:
        - file: /tmp/new.qcow2
          snapshot: off
